const products=[{id:1,name:'Chicken Burger',price:450,cat:'fast',icon:'🍔',desc:'Juicy chicken burger with fresh salad.'},{id:2,name:'Chicken Biryani',price:350,cat:'main',icon:'🍛',desc:'Aromatic rice with tender chicken.'},{id:3,name:'Cheese Pizza',price:900,cat:'fast',icon:'🍕',desc:'Cheesy pizza prepared fresh.'},{id:4,name:'Chicken Roll',price:250,cat:'fast',icon:'🌯',desc:'Crispy roll with seasoned chicken.'},{id:5,name:'French Fries',price:180,cat:'side',icon:'🍟',desc:'Golden crispy potato fries.'},{id:6,name:'Cold Drink',price:120,cat:'drink',icon:'🥤',desc:'Refreshing chilled drink.'}];
let cart=JSON.parse(localStorage.getItem('easyFoodCart')||'[]');const menuGrid=document.getElementById('menuGrid'),cartList=document.getElementById('cartList'),cartCount=document.getElementById('cartCount'),cartTotal=document.getElementById('cartTotal'),cartEl=document.getElementById('cart'),backdrop=document.getElementById('backdrop'),toast=document.getElementById('toast');const money=n=>`Rs ${n.toLocaleString()}`;
function renderMenu(filter='all'){const list=filter==='all'?products:products.filter(p=>p.cat===filter);menuGrid.innerHTML=list.map(p=>`<article class="food"><div class="food-image">${p.icon}</div><div class="food-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="food-row"><span class="price">${money(p.price)}</span><button class="add" onclick="addItem(${p.id})">Add to cart</button></div></div></article>`).join('')}
function addItem(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();openCart();showToast('Added to your cart')}
function changeQty(id,amount){const item=cart.find(x=>x.id===id);if(!item)return;item.qty+=amount;if(item.qty<1)cart=cart.filter(x=>x.id!==id);save()}
function save(){localStorage.setItem('easyFoodCart',JSON.stringify(cart));renderCart()}
function renderCart(){let total=0,count=0;if(!cart.length){cartList.innerHTML='<div class="empty">Your cart is empty.<br>Add something delicious from the menu.</div>'}else{cartList.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id),line=p.price*x.qty;total+=line;count+=x.qty;return `<div class="cart-item"><div><strong>${p.name}</strong><small>${money(p.price)} × ${x.qty}</small></div><div class="qty"><button onclick="changeQty(${p.id},-1)" aria-label="Decrease">−</button><button onclick="changeQty(${p.id},1)" aria-label="Increase">+</button></div></div>`}).join('')}cartCount.textContent=count;cartTotal.textContent=money(total)}
function openCart(){cartEl.classList.add('open');backdrop.classList.add('show')}function closeCart(){cartEl.classList.remove('open');backdrop.classList.remove('show')}function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderMenu(btn.dataset.filter)}));
document.getElementById('cartButton').onclick=openCart;document.getElementById('contactButton').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;backdrop.onclick=closeCart;document.getElementById('mobileMenu').onclick=()=>document.getElementById('nav').classList.toggle('open');
document.getElementById('copyPayment').onclick=async()=>{try{await navigator.clipboard.writeText('03702283429');showToast('Payment number copied')}catch(e){showToast('Payment number: 03702283429')}};
document.getElementById('checkout').onclick=()=>{if(!cart.length){showToast('Please add an item first');return}const order=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `${p.name} x ${x.qty}`}).join(', ');alert(`Order summary:\n${order}\n\nTotal: ${cartTotal.textContent}\n\nPayment: EasyPaisa / JazzCash\nAccount: 03702283429\n\nPlease confirm your delivery details with the Easy Food team.`)};
document.getElementById('year').textContent=new Date().getFullYear();renderMenu();renderCart();