const foods=[{id:1,name:'Chicken Burger',desc:'Juicy chicken burger with fresh salad.',price:450,icon:'🍔'},{id:2,name:'Chicken Biryani',desc:'Aromatic rice with tender chicken.',price:350,icon:'🍛'},{id:3,name:'Pizza',desc:'Freshly prepared cheesy pizza.',price:900,icon:'🍕'},{id:4,name:'Chicken Roll',desc:'Crispy roll with seasoned chicken.',price:250,icon:'🌯'},{id:5,name:'Fries',desc:'Golden crispy potato fries.',price:180,icon:'🍟'},{id:6,name:'Cold Drink',desc:'Refreshing chilled drink.',price:120,icon:'🥤'}];
let cart=JSON.parse(localStorage.getItem('easyFoodCart')||'[]');
const grid=document.getElementById('foodGrid'),count=document.getElementById('cartCount'),items=document.getElementById('cartItems'),total=document.getElementById('cartTotal');
function money(n){return `Rs ${n.toLocaleString()}`}
function save(){localStorage.setItem('easyFoodCart',JSON.stringify(cart));renderCart()}
function add(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();openCart()}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save()}
function renderFood(){grid.innerHTML=foods.map(f=>`<article class="food-card"><div class="food-img">${f.icon}</div><div class="food-info"><h3>${f.name}</h3><p>${f.desc}</p><div class="price-row"><span class="price">${money(f.price)}</span><button class="add" onclick="add(${f.id})">Add +</button></div></div></article>`).join('')}
function renderCart(){let sum=0,qty=0;items.innerHTML=cart.length?cart.map(c=>{const f=foods.find(x=>x.id===c.id),line=f.price*c.qty;sum+=line;qty+=c.qty;return `<div class="cart-item"><div><strong>${f.name}</strong><small>${money(f.price)} × ${c.qty}</small></div><div class="qty"><button onclick="change(${f.id},-1)">−</button> <button onclick="change(${f.id},1)">+</button></div></div>`}).join(''):'<p style="color:#66736d">Your cart is empty.</p>';count.textContent=qty;total.textContent=money(sum)}
const panel=document.getElementById('cartPanel'),overlay=document.getElementById('overlay');
function openCart(){panel.classList.add('open');overlay.classList.add('show');panel.setAttribute('aria-hidden','false')}
function closeCart(){panel.classList.remove('open');overlay.classList.remove('show');panel.setAttribute('aria-hidden','true')}
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;overlay.onclick=closeCart;document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');
document.getElementById('orderBtn').onclick=()=>{if(!cart.length){alert('Please add food to your cart first.');return}const lines=cart.map(c=>{const f=foods.find(x=>x.id===c.id);return `${f.name} x ${c.qty}`}).join(', ');alert(`Your order is ready: ${lines}\nTotal: ${total.textContent}\n\nPlease contact the Easy Food team to confirm delivery details and payment.`)};
document.getElementById('year').textContent=new Date().getFullYear();renderFood();renderCart();
